-- AlterTable
ALTER TABLE "Fill" ALTER COLUMN "quantity" SET DATA TYPE TEXT,
ALTER COLUMN "price" SET DATA TYPE TEXT,
ALTER COLUMN "long" SET DATA TYPE TEXT,
ALTER COLUMN "short" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "availableBalance" SET DEFAULT '0',
ALTER COLUMN "availableBalance" SET DATA TYPE TEXT,
ALTER COLUMN "lockedBalance" SET DEFAULT '0',
ALTER COLUMN "lockedBalance" SET DATA TYPE TEXT;
